# This is a basic workflow to help you get started with Actions

name: raspberry-pi-benchmark

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, raspberry]
    container:
      image: ubuntu:jammy
      options: --privileged
      volumes:
        - /dev:/dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install requirements for actions/checkout
        run: |
          apt-get update
          apt-get install build-essential -y
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Performs rpi benchmark
        run: |
          pip install evdev
          python ./listUsbDevices.py
        # run: |
        #   apt update
        #   apt -y install curl
        #   curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | bash
        #   apt -y install sysbench
        #   sysbench cpu --threads=4 run
